apiVersion: v1
kind: Service
metadata:
  name: ${{ values.appName }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.appName }}
    backstage.io/kubernetes-id: ${{ values.appName }}
spec:
  type: ClusterIP
  selector:
    app: ${{ values.appName }}
  ports:
    - port: 8080
      protocol: TCP
      name: http

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${{ values.appName }}
  namespace: ${{ values.namespace }}
spec:
  to:
    kind: Service
    name: ${{ values.appName }}
  port:
    targetPort: 8080
  tls:
    termination: edge